# Generated by Django 3.0.5 on 2020-04-27 12:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='profile',
            name='imagem_bio',
            field=models.ImageField(default='static/img/author_image.png', upload_to='profile_pics/bio_pics'),
        ),
    ]
