# Generated by Django 3.0.5 on 2020-04-28 21:38

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0002_profile_imagem_bio'),
    ]

    operations = [
        migrations.AddField(
            model_name='post',
            name='referencia',
            field=models.CharField(default=django.utils.timezone.now, max_length=1000),
            preserve_default=False,
        ),
    ]
