# Generated by Django 3.0.5 on 2020-05-04 19:16

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0006_auto_20200504_1914'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='contact',
            name='nome',
        ),
    ]
