# Generated by Django 3.0.5 on 2020-05-05 19:53

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0007_remove_contact_nome'),
    ]

    operations = [
        migrations.AddField(
            model_name='contact',
            name='imagem',
            field=models.ImageField(default=django.utils.timezone.now, upload_to='profile_pics/bio_pics'),
            preserve_default=False,
        ),
    ]
