# Generated by Django 3.0.5 on 2020-05-05 19:58

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0008_contact_imagem'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='contact',
            name='imagem',
        ),
    ]
