# Generated by Django 3.0.5 on 2020-05-05 20:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0009_remove_contact_imagem'),
    ]

    operations = [
        migrations.AlterField(
            model_name='post',
            name='imagem',
            field=models.ImageField(upload_to='post_pics'),
        ),
    ]
