# Generated by Django 3.0.5 on 2020-05-06 13:56

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0011_auto_20200506_1354'),
    ]

    operations = [
        migrations.RenameField(
            model_name='profile',
            old_name='bio_usuario',
            new_name='Biografia',
        ),
    ]
