# Generated by Django 3.0.5 on 2020-05-06 13:56

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0012_auto_20200506_1356'),
    ]

    operations = [
        migrations.RenameField(
            model_name='profile',
            old_name='Biografia',
            new_name='biografia',
        ),
    ]
