# Generated by Django 3.0.5 on 2020-05-11 12:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0015_profile_nome'),
    ]

    operations = [
        migrations.AlterField(
            model_name='post',
            name='referencia',
            field=models.CharField(default='none', max_length=1000),
        ),
    ]
