# Generated by Django 3.0.5 on 2020-05-11 12:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0016_auto_20200511_1240'),
    ]

    operations = [
        migrations.AlterField(
            model_name='post',
            name='referencia',
            field=models.URLField(default='none', max_length=500),
        ),
    ]
