# Generated by Django 3.0.5 on 2020-05-26 10:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0017_auto_20200511_1258'),
    ]

    operations = [
        migrations.AddField(
            model_name='post',
            name='ficheiro',
            field=models.FileField(default='none', upload_to='documents'),
        ),
    ]
